name: android-ci
on:
  pull_request:
    branches:
      - master
      - 'dev'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    environment: Android CI/CD
    
    steps:
      - uses: actions/checkout@v2

      - name: Create LocalProperites
        env:
          CREDENTIAL_WEB_CLIENT_ID: ${{ secrets.CREDENTIAL_WEB_CLIENT_ID }}
          MISSION_MATE_BASE_URL: ${{ secrets.MISSION_MATE_BASE_URL }}
        run: |
          echo CREDENTIAL_WEB_CLIENT_ID=\"$CREDENTIAL_WEB_CLIENT_ID\" > ./local.properties
          echo MISSION_MATE_BASE_URL=\"$MISSION_MATE_BASE_URL\" >> ./local.properties
      
      - name: Generate Keystore file from Github Secrets
        env:
          KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE" > ./mission-mate-keystore.b64
          base64 -d -i ./mission-mate-keystore.b64 > ./mission-mate-keystore.jks  
      
      - name: Build with Gradle
        run: fastlane test
